package com.ricy40.songe.core.init;

import com.ricy40.songe.Songe;

import com.ricy40.songe.common.VerticalSlabBlock;
import com.ricy40.songe.common.blocks.*;
import com.ricy40.songe.core.interfaces.WeatheringCopper;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.common.ToolType;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.Properties;
import java.util.function.Supplier;

public class BlockInit {

	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Songe.MOD_ID);

	//Test Songe Set

	public static final RegistryObject<Block> SONGE_BLOCK = registerBlock("songe_block", () -> new SongeBlock(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));
	public static final RegistryObject<Block> SONGE_STAIRS = registerBlock("songe_stairs", () -> new SongeStairs(() -> SONGE_BLOCK.get().defaultBlockState(), AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));
	public static final RegistryObject<Block> SONGE_FENCE = registerBlock("songe_fence", () -> new SongeFence(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));
	public static final RegistryObject<Block> SONGE_FENCE_GATE = registerBlock("songe_fence_gate", () -> new SongeFenceGate(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops()));
	public static final RegistryObject<Block> SONGE_SLAB = registerBlock("songe_slab", () -> new SongeSlab(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));
	public static final RegistryObject<Block> SONGE_VERTICAL_SLAB = registerBlock("songe_vertical_slab", () -> new SongeVerticalSlab(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));
	public static final RegistryObject<Block> SONGE_BUTTON = registerBlock("songe_button", () -> new StoneButtonBlock(AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS).noCollission()));
	public static final RegistryObject<Block> SONGE_PRESSURE_PLATE = registerBlock("songe_pressure_plate", () -> new PressurePlateBlock(PressurePlateBlock.Sensitivity.EVERYTHING, AbstractBlock.Properties.of(Material.SPONGE, MaterialColor.COLOR_YELLOW).strength(0.6f, 0.6f).harvestTool(ToolType.HOE).harvestLevel(1).requiresCorrectToolForDrops().sound(SoundType.GRASS)));

	//Copper

	public static final RegistryObject<Block> COPPER_BLOCK = registerBlock("copper_block", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER = registerBlock("exposed_copper", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER = registerBlock("weathered_copper", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER = registerBlock("oxidized_copper", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_SLAB = registerBlock("copper_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_SLAB = registerBlock("exposed_copper_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_SLAB = registerBlock("weathered_copper_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_SLAB = registerBlock("oxidized_copper_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_STAIRS = registerBlock("copper_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.UNAFFECTED, COPPER_BLOCK.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_STAIRS = registerBlock("exposed_copper_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.EXPOSED, EXPOSED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_STAIRS = registerBlock("weathered_copper_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.WEATHERED, WEATHERED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_STAIRS = registerBlock("oxidized_copper_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.OXIDIZED, OXIDIZED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_VERTICAL_SLAB = registerBlock("copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_VERTICAL_SLAB = registerBlock("exposed_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_VERTICAL_SLAB = registerBlock("weathered_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_VERTICAL_SLAB = registerBlock("oxidized_copper_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	
	//Tiles

	public static final RegistryObject<Block> COPPER_TILES = registerBlock("copper_tiles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_TILES = registerBlock("exposed_copper_tiles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_TILES = registerBlock("weathered_copper_tiles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_TILES = registerBlock("oxidized_copper_tiles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_TILES_SLAB = registerBlock("copper_tiles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_TILES_SLAB = registerBlock("exposed_copper_tiles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_TILES_SLAB = registerBlock("weathered_copper_tiles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_TILES_SLAB = registerBlock("oxidized_copper_tiles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_TILES_STAIRS = registerBlock("copper_tiles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.UNAFFECTED, COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_TILES_STAIRS = registerBlock("exposed_copper_tiles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.EXPOSED, EXPOSED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_TILES_STAIRS = registerBlock("weathered_copper_tiles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.WEATHERED, WEATHERED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_TILES_STAIRS = registerBlock("oxidized_copper_tiles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.OXIDIZED, OXIDIZED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_TILES_VERTICAL_SLAB = registerBlock("copper_tiles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_TILES_VERTICAL_SLAB = registerBlock("exposed_copper_tiles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_TILES_VERTICAL_SLAB = registerBlock("weathered_copper_tiles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_TILES_VERTICAL_SLAB = registerBlock("oxidized_copper_tiles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	
	//Shingles

	public static final RegistryObject<Block> COPPER_SHINGLES = registerBlock("copper_shingles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_SHINGLES = registerBlock("exposed_copper_shingles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_SHINGLES = registerBlock("weathered_copper_shingles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_SHINGLES = registerBlock("oxidized_copper_shingles", () -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_SHINGLES_SLAB = registerBlock("copper_shingles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_SHINGLES_SLAB = registerBlock("exposed_copper_shingles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_SHINGLES_SLAB = registerBlock("weathered_copper_shingles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_SHINGLES_SLAB = registerBlock("oxidized_copper_shingles_slab", () -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_SHINGLES_STAIRS = registerBlock("copper_shingles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.UNAFFECTED, COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_SHINGLES_STAIRS = registerBlock("exposed_copper_shingles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.EXPOSED, EXPOSED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_SHINGLES_STAIRS = registerBlock("weathered_copper_shingles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.WEATHERED, WEATHERED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_SHINGLES_STAIRS = registerBlock("oxidized_copper_shingles_stairs", () -> new WeatheringCopperStairsBlock(WeatheringCopper.WeatherState.OXIDIZED, OXIDIZED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("copper_shingles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> EXPOSED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("exposed_copper_shingles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.EXPOSED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.TERRACOTTA_LIGHT_GRAY).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WEATHERED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("weathered_copper_shingles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.WEATHERED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_STEM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> OXIDIZED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("oxidized_copper_shingles_vertical_slab", () -> new WeatheringCopperVerticalSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, AbstractBlock.Properties.of(Material.METAL, MaterialColor.WARPED_NYLIUM).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));

	//Waxed Copper

	public static final RegistryObject<Block> WAXED_COPPER_BLOCK = registerBlock("waxed_copper_block", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER = registerBlock("waxed_exposed_copper", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER = registerBlock("waxed_weathered_copper", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER = registerBlock("waxed_oxidized_copper", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_SLAB = registerBlock("waxed_copper_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_SLAB = registerBlock("waxed_exposed_copper_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_SLAB = registerBlock("waxed_weathered_copper_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_SLAB = registerBlock("waxed_oxidized_copper_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_STAIRS = registerBlock("waxed_copper_stairs", () -> new WaxingCopperStairsBlock(WAXED_COPPER_BLOCK.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_STAIRS = registerBlock("waxed_exposed_copper_stairs", () -> new WaxingCopperStairsBlock(WAXED_EXPOSED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_STAIRS = registerBlock("waxed_weathered_copper_stairs", () -> new WaxingCopperStairsBlock(WAXED_WEATHERED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_STAIRS = registerBlock("waxed_oxidized_copper_stairs", () -> new WaxingCopperStairsBlock(WAXED_OXIDIZED_COPPER.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_VERTICAL_SLAB = registerBlock("waxed_copper_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_VERTICAL_SLAB = registerBlock("waxed_exposed_copper_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_VERTICAL_SLAB = registerBlock("waxed_weathered_copper_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_VERTICAL_SLAB = registerBlock("waxed_oxidized_copper_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));

	//Waxed Tiles

	public static final RegistryObject<Block> WAXED_COPPER_TILES = registerBlock("waxed_copper_tiles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_TILES = registerBlock("waxed_exposed_copper_tiles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_TILES = registerBlock("waxed_weathered_copper_tiles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_TILES = registerBlock("waxed_oxidized_copper_tiles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_TILES_SLAB = registerBlock("waxed_copper_tiles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_TILES_SLAB = registerBlock("waxed_exposed_copper_tiles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_TILES_SLAB = registerBlock("waxed_weathered_copper_tiles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_TILES_SLAB = registerBlock("waxed_oxidized_copper_tiles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_TILES_STAIRS = registerBlock("waxed_copper_tiles_stairs", () -> new WaxingCopperStairsBlock(WAXED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_TILES_STAIRS = registerBlock("waxed_exposed_copper_tiles_stairs", () -> new WaxingCopperStairsBlock(WAXED_EXPOSED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_TILES_STAIRS = registerBlock("waxed_weathered_copper_tiles_stairs", () -> new WaxingCopperStairsBlock(WAXED_WEATHERED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_TILES_STAIRS = registerBlock("waxed_oxidized_copper_tiles_stairs", () -> new WaxingCopperStairsBlock(WAXED_OXIDIZED_COPPER_TILES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_TILES_VERTICAL_SLAB = registerBlock("waxed_copper_tiles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_TILES_VERTICAL_SLAB = registerBlock("waxed_exposed_copper_tiles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_TILES_VERTICAL_SLAB = registerBlock("waxed_weathered_copper_tiles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_TILES_VERTICAL_SLAB = registerBlock("waxed_oxidized_copper_tiles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));

	//Waxed Shingles

	public static final RegistryObject<Block> WAXED_COPPER_SHINGLES = registerBlock("waxed_copper_shingles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_SHINGLES = registerBlock("waxed_exposed_copper_shingles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_SHINGLES = registerBlock("waxed_weathered_copper_shingles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_SHINGLES = registerBlock("waxed_oxidized_copper_shingles", () -> new WaxingCopperFullBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_SHINGLES_SLAB = registerBlock("waxed_copper_shingles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_SHINGLES_SLAB = registerBlock("waxed_exposed_copper_shingles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_SHINGLES_SLAB = registerBlock("waxed_weathered_copper_shingles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_SHINGLES_SLAB = registerBlock("waxed_oxidized_copper_shingles_slab", () -> new WaxingCopperSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_SHINGLES_STAIRS = registerBlock("waxed_copper_shingles_stairs", () -> new WaxingCopperStairsBlock(WAXED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_SHINGLES_STAIRS = registerBlock("waxed_exposed_copper_shingles_stairs", () -> new WaxingCopperStairsBlock(WAXED_EXPOSED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_SHINGLES_STAIRS = registerBlock("waxed_weathered_copper_shingles_stairs", () -> new WaxingCopperStairsBlock(WAXED_WEATHERED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_SHINGLES_STAIRS = registerBlock("waxed_oxidized_copper_shingles_stairs", () -> new WaxingCopperStairsBlock(WAXED_OXIDIZED_COPPER_SHINGLES.get().defaultBlockState(), AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("waxed_copper_shingles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_EXPOSED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("waxed_exposed_copper_shingles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_WEATHERED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("waxed_weathered_copper_shingles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));
	public static final RegistryObject<Block> WAXED_OXIDIZED_COPPER_SHINGLES_VERTICAL_SLAB = registerBlock("waxed_oxidized_copper_shingles_vertical_slab", () -> new WaxingCopperVerticalSlabBlock(AbstractBlock.Properties.of(Material.METAL, MaterialColor.COLOR_ORANGE).requiresCorrectToolForDrops().strength(3.0F, 6.0F).sound(SoundInit.COPPER)));

	//Raw Stuff

	public static final RegistryObject<Block> RAW_SILVER_BLOCK = registerBlock("raw_silver_block", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.STONE).strength(5f, 6f).harvestTool(ToolType.PICKAXE).harvestLevel(1).harvestTool(ToolType.PICKAXE)));
	public static final RegistryObject<Block> RAW_THALLASIUM_BLOCK = registerBlock("raw_thallasium_block", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.STONE).strength(5f, 6f).harvestTool(ToolType.PICKAXE).harvestLevel(1).harvestTool(ToolType.PICKAXE)));
	public static final RegistryObject<Block> RAW_ZINC_BLOCK = registerBlock("raw_zinc_block", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.STONE).strength(5f, 6f).harvestTool(ToolType.PICKAXE).harvestLevel(1).harvestTool(ToolType.PICKAXE)));

	//Vertical Slabs

	public static final RegistryObject<Block> ANDESITE_COBBLESTONE_VERTICAL_SLAB = registerBlock("andesite_cobblestone_vertical_slab", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.STONE).strength(6.0f, 1.5f).harvestTool(ToolType.PICKAXE).requiresCorrectToolForDrops().harvestLevel(1).sound(SoundType.STONE)));
	public static final RegistryObject<Block> DIORITE_COBBLESTONE_VERTICAL_SLAB = registerBlock("diorite_cobblestone_vertical_slab", () -> new Block(AbstractBlock.Properties.of(Material.STONE, MaterialColor.STONE).strength(6.0f, 1.5f).harvestTool(ToolType.PICKAXE).requiresCorrectToolForDrops().harvestLevel(1).sound(SoundType.STONE)));

	//Register Method

	public static <T extends Block>RegistryObject<T> registerBlock(String name, Supplier<T> block) {
		RegistryObject<T> toReturn = BLOCKS.register(name, block);
		registerBlockItem(name, toReturn);
		return toReturn;
	}

	private static <T extends Block > void registerBlockItem(String name, RegistryObject<T> block) {
		ItemInit.ITEMS.register(name, () -> new BlockItem(block.get(),
				new Item.Properties().tab(Songe.SONGE_GROUP)));
	}
}